provinces = {
        'Buenos Aires': 'buenos_aires_4.db',
        'Catamarca': 'catamarca_4.db',
        'Chaco': 'chaco_4.db',
        'Chubut': 'chubut_4.db',
        'Cordoba': 'cordoba_4.db',
        'Corrientes': 'corrientes_4.db',
        'Entre Rios': 'entre_rios_4.db',
        'Formosa': 'formosa_4.db',
        'Jujuy': 'jujuy_4.db',
        'La Pampa': 'la_pampa_4.db',
        'La Rioja': 'la_rioja_4.db',
        'Mendoza': 'mendoza_4.db',
        'Misiones': 'misiones_4.db',
        'Neuquen': 'neuquen_4.db',
        'Rio Negro': 'rio_negro_4.db',
        'Salta': 'salta_4.db',
        'San Juan': 'san_juan_4.db',
        'San Luis': 'san_luis_4.db',
        'Santa Cruz': 'santa_cruz_4.db',
        'Santa Fe': 'santa_fe_4.db',
        'Santiago del Estero': 'santiago_del_estero_4.db',
        'Tierra del Fuego': 'tierra_del_fuego_4.db',
        'Tucuman': 'tucuman_4.db'
    }